-- table
CREATE TABLE IF NOT EXISTS users (
    "id" SERIAL PRIMARY KEY,
    "uuid" VARCHAR(255) NOT NULL UNIQUE,

    "email" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,

    "is_deleted" BOOLEAN DEFAULT FALSE NOT NULL,
   
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()::TIMESTAMPTZ,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()::TIMESTAMPTZ
);

